version: "3"
services:
  mysqlDB:
    image: mysql
    container_name: mysqlDB
    environment:
      MYSQL_DATABASE: anonymous_board
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: user01
      MYSQL_USER_PASSWORD: user01
    ports:
      - 3306:3306
    networks:
      - backend_net

  app:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mysqlDB
    networks:
      - backend_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlDB:3306/anonymous_board?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: user01
      SPRING_DATASOURCE_PASSWORD: user01

networks:
  backend_net:
